from  tkinter import *
root = Tk()
root.title("Simple calculator")
input = Entry (root  , width= 70 , borderwidth= 3 ,)
input.grid( row= 0 , column=0  ,columnspan = 3 , padx = 10 , pady = 10 )

def button_click(number):
    # input.delete(0 , END)
    current = input.get()
    input.delete( 0 , END)
    input.insert( 0 ,str (current) + str(number))
    if number ==  "clear":
        input.delete( 0 ,END)
button_1 = Button (root , text= "1" , padx= 30 , pady=20 ,command = lambda :button_click(1))
button_2 = Button (root , text= "2" , padx= 30 , pady=20 ,command = lambda :button_click(2))
button_3 = Button (root , text= "3" , padx= 30 , pady=20 ,command = lambda :button_click(3))
button_4 = Button (root , text= "4" , padx= 30 , pady=20 ,command = lambda :button_click(4))
button_5 = Button (root , text= "5" , padx= 30 , pady=20 ,command = lambda :button_click(5))
button_6 = Button (root , text= "6" , padx= 30 , pady=20 ,command = lambda :button_click(6))
button_7 = Button (root , text= "7" , padx= 30 , pady=20 ,command = lambda :button_click(7))
button_8 = Button (root , text= "8" , padx= 30 , pady=20 ,command = lambda :button_click(8))
button_9 = Button (root , text= "9" , padx= 30 , pady=20 ,command = lambda :button_click(9))
button_0 = Button (root , text = "0" ,padx=30 , pady= 20, command= lambda :button_click(0))
button_equal = Button (root , text = "=" ,padx = 95,pady= 20 ,command= lambda :button_click(), fg = "white" , bg = "green" ,font ="Consolas 16")
button_clear = Button (root , text = "Clear" , padx = 90 , pady = 20 , command= lambda :button_click("clear") , fg = "white" , bg = "red" , font ="Consolas 12" )
button_addtion = Button(root , text= "+" , padx = 30 , pady = 20 , command=lambda :button_click() )
button_1.grid(row = 3 , column = 0)
button_2.grid(row = 3 , column = 1)
button_3.grid(row = 3 , column = 2)
button_4.grid(row = 4 , column = 0)
button_5.grid(row = 4 , column = 1)
button_6.grid(row = 4 , column = 2)
button_7.grid(row = 5 , column = 0)
button_8.grid(row = 5 , column  = 1)
button_9.grid(row = 5 , column = 2)
button_0.grid(row = 6 , column = 0)
button_equal.grid (row = 6 , column = 1 , columnspan = 2)
button_clear.grid(row = 7  , column = 1 , columnspan = 2)
button_addtion.grid(row = 7 ,column = 0)


root.mainloop()